config/routes.rb
Rails.application.routes.draw do
    resources :tactivities
    root 'tactivities#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tactivity.rb
class Tactivity < ApplicationRecord
end

app/models/teaching_activity.rb
class TeachingActivity < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tactivities_controller.rb
class TactivitiesController < ApplicationController
    before_action :find_tactivity, only: [:show, :edit, :update, :destroy]
    
    def index
        @tactivities = Tactivity.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
        @tactivity = Tactivity.new
    end
    
    def create
        @tactivity = Tactivity.new(tactivity_params)
        if @tactivity.save
            redirect_to @tactivity
        else 
            render 'new'
        end 
    end
    
    def edit
    end
    
    def update
        if @tactivity.update(tactivity_params)
            redirect_to @tactivity
        else 
            render 'edit'
        end 
    end 
    
    def destroy
        @tactivity.destroy
        redirect_to root_path
    end 
    
    private
    
    def tactivity_params
        params.require(:tactivity).permit(:date, :name, :ta1, :ta2, :ta3, :ta4, :status)
    end 
    
    def find_tactivity
        @tactivity = Tactivity.find(params[:id])
    end 
end

app/controllers/teaching_activities_controller.rb
class TeachingActivitiesController < ApplicationController
    before_action :find_tactivity, only: [:show, :edit, :update, :destroy]
    
    def index
        @teaching_activities = TeachingActivity.all.order("created_at DESC")
    end
    
    def show
    end
    
    def new
        @teaching_activity = TeachingActivity.new
    end
    
    def create
        @teaching_activity = TeachingActivity.new(tactivity_params)
        if @teaching_activity.save
            redirect_to @teaching_activity
        else 
            render 'new'
        end 
    end
    
    def edit
    end
    
    def update
    end 
    
    def destroy
    end 
    
    private
    
    def tactivity_params
        params.require(:teaching_activity).permit(:date, :name, :ta1, :ta2, :ta3, :ta4, :status)
    end 
    
    def find_tactivity
        @teaching_activity = TeachingActivity.find(params[:id])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tactivities_helper.rb
module TactivitiesHelper
end

app/helpers/teaching_activities_helper.rb
module TeachingActivitiesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MyBlueberry
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body
    %nav.navbar-default
      .container
        .navbar-header
          = link_to "Home", root_path, class: "navbar-brand"
        .nav.navbar-nav.navbar-right
          = link_to "New", new_tactivity_path, class: "navbar navbar-link"
    .container   
      = yield

app/views/tactivities/_tform.html.haml
= simple_form_for(@tactivity, html: {class: 'form-control'}) do |f|
    = f.input :name, label: "Name", input_html: { class: "form-control" }
    = f.input :date, label: "Date", input_html: { class: "form-control" }
    = f.input :ta1, label: "Please describe your activities and experience as a teacher during the year. Elaborate on pedagogical activities, curricular transformation or revision and new course development.", input_html: { class: "form-control" }
    = f.input :ta2, label: "Please read your teaching evaluations for both semesters of the past calendar year and comment on them here. Are there any suggestions which you find useful and intend to incorporate into your courses in the future? Are there any comments which you wish to refute or explain?", input_html: { class: "form-control" }
    = f.input :ta3, label: "For each one of the courses you have taught in the spring and fall of the last calendar year, please indicate how well your students are achieving the learning outcomes of your courses and the learning outcomes of the majors/programs your courses contribute to; include any evidence you have. Do you envisage making any changes in your courses as a result of assessment activities, or for any other reasons? Please, also consult with your chair about any assessment information he/she may need from you to complete the departmental report.", input_html: { class: "form-control" }
    = f.input :ta4, label: "Any other comments you would like to make about your teaching? "
    %br/
    = f.button :submit
    = link_to "Cancel", root_path

app/views/tactivities/edit.html.haml
%h1 Update Teaching Activity

= render 'tform'

app/views/tactivities/index.html.haml
%h1 Teaching Activities

- @tactivities.each do |tactivity|
    %h3= link_to tactivity.name, tactivity
    %p= tactivity.date
    
    

app/views/tactivities/new.html.haml
%h1 New Teaching Activity

= render 'tform'

app/views/tactivities/show.html.haml
#teaching_activity
    %h1= @tactivity.name
    %h3= @tactivity.date
    %p= @tactivity.ta1
    %p= @tactivity.ta2
    %p= @tactivity.ta3
    %p= @tactivity.ta4
    
= link_to "Edit", edit_tactivity_path(@tactivity)
= link_to "Delete", tactivity_path(@tactivity), method: :delete, data: {confirm: "Are you sure?"}

app/views/teaching_activities/_tform.html.haml
= simple_form_for(@teaching_activity, html: {class: 'form-control'}) do |f|
    = f.input :name, label: "Name", input_html: { class: "form-control" }
    = f.input :date, label: "Date", input_html: { class: "form-control" }
    = f.input :ta1, label: "Please describe your activities and experience as a teacher during the year. Elaborate on pedagogical activities, curricular transformation or revision and new course development.", input_html: { class: "form-control" }
    = f.input :ta2, label: "Please read your teaching evaluations for both semesters of the past calendar year and comment on them here. Are there any suggestions which you find useful and intend to incorporate into your courses in the future? Are there any comments which you wish to refute or explain?", input_html: { class: "form-control" }
    = f.input :ta3, label: "For each one of the courses you have taught in the spring and fall of the last calendar year, please indicate how well your students are achieving the learning outcomes of your courses and the learning outcomes of the majors/programs your courses contribute to; include any evidence you have. Do you envisage making any changes in your courses as a result of assessment activities, or for any other reasons? Please, also consult with your chair about any assessment information he/she may need from you to complete the departmental report.", input_html: { class: "form-control" }
    = f.input :ta4, label: "Any other comments you would like to make about your teaching? "
    %br/
    = f.button :submit
    = link_to "Cancel", root_path

app/views/teaching_activities/index.html.haml
%h1 Teaching Activities

- @teaching_activities.each do |tactivity|
    %h2= tactivity.name
    %p= tactivity.date

app/views/teaching_activities/show.html.haml
#teaching_activity
    %p= @teaching_activity.name
    %p= @teaching_activity.date
    %p= @teaching_activity.ta1
    %p= @teaching_activity.ta2
    %p= @teaching_activity.ta3
    %p= @teaching_activity.ta4